obj1:
    name: 'floor'
    file: '$(find tennis)/model/grass_court.body'
    translation: [10, 0, -0.1]
obj2:
    name: 'ball'
    file: '$(find tennis)/model/tennis_ball.body'
    translation: [-1, 0, 0]
